version: '3'

networks:
  default:
    driver: bridge

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  web:
    build:
      context: .
    command: bash -c "python server.py"
    volumes:
        - .:/code
    ports:
        - "8080:8080"
    depends_on:
        - db
