version: '3'

networks:
  default:
    driver: bridge

services:
  web:
    build:
      context: .
    command: bash -c "alembic upgrade head && python server.py"
    volumes:
        - .:/code
    ports:
        - "8080:8080"
    depends_on:
        - db

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
